spring:
  cloud:
    gateway:
      discovery:
        locator:
          # lower-case-service-id: true
          enabled: true
      routes:
        - id: candidat-s
          uri: http://localhost:8082/
          predicates:
            - Path=/candidats/**

        - id: post-service
          uri: http://localhost:8088/
          predicates:
            - Path=/**


