spring:
  cloud:
    gateway:
      discovery:
        locator:
          # lower-case-service-id: true
          enabled: true
      routes:
        - id: MICORITEM-S
          uri: http://localhost:8055/
          predicates:
            - Path=/MICORITEM-S/**

        - id: MSTRADE-S
          uri: http://localhost:8086/
          predicates:
            - Path=/MSTRADE-S/**

        - id: post-service
          uri: http://localhost:8088/
          predicates:
            - Path=/POST-SERVICE/**

        - id: MicroOrganisation-s
          uri: http://localhost:8044/
          predicates:
            - Path=/MicroOrganisation-s/**     USER-SERVICE

        - id: COMPLAINT-SERVICE
          uri: http://localhost:5000/
          predicates:
            - Path=/COMPLAINT-SERVICE/**

        - id: USER-SERVICE
          uri: http://localhost:8075/
          predicates:
            - Path=/USER-SERVICE/**

