spring:
  cloud:
    gateway:
      discovery:
        locator:
          # lower-case-service-id: true
          enabled: true
      routes:
        - id: MICORITEM-S
          uri: http://localhost:8055/
          predicates:
            - Path=/MICORITEM-S/**

        - id: MSTRADE-S
          uri: http://localhost:8086/
          predicates:
            - Path=/MSTRADE-S/**

        - id: post-service
          uri: http://localhost:8088/
          predicates:
            - Path=/POST-SERVICE/**

        - id: MicroOrganisation-s
          uri: http://localhost:9090/
          predicates:
            - Path=/MicroOrganisation-s/**

